openapi: 3.0.2
info:
  title: User API
  description: API to manage users.
  version: 1.0.0
servers:
  - url: 'http://localhost:{port}'
    variables:
      port:
        enum:
          - '7000'
        default: '7000'

paths:
  /users/{userId}:
    get:
      operationId: getUserById
      summary: Find user by ID
      description: Returns user based on ID
      parameters:
        - $ref: 'components.yaml#/components/parameters/userId'
      responses:
        '200':
          description: Returns user for the provided ID
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/User'
